# Generated by Django 6.0.7 on 2026-07-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('award', 'Awards'), ('recognition', 'Recognitions'), ('invited_talk', 'Invited Talks'), ('conference', 'Conferences'), ('certification', 'Certifications'), ('honor', 'Professional Honors')], max_length=20)),
                ('issuing_organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
