# Generated by Django 6.0.7 on 2026-07-22 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('award', 'Award'), ('recognition', 'Recognition'), ('invited_talk', 'Invited Talk'), ('conference', 'Conference'), ('certification', 'Certification'), ('honor', 'Professional Honor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(help_text='Full date required — for year-only facts, use the 1st of January (e.g. 2011-01-01). Templates display just the year via |date:"Y".'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category'], name='achievement_categor_a7059b_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['date'], name='achievement_date_9e638d_idx'),
        ),
    ]
