# Generated by Django 6.0.7 on 2026-07-21 22:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('preorder', 'Pre-order'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('purchase_url', models.URLField(blank=True)),
                ('featured_order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
            ],
        ),
    ]
