# Generated by Django 6.0.7 on 2026-07-21 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Category',
                'verbose_name_plural': 'Contact Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Department of Engineering', max_length=255)),
                ('university', models.CharField(default='University of Cambridge', max_length=255)),
                ('street', models.CharField(default='Trumpington Street', max_length=255)),
                ('postcode', models.CharField(default='CB2 1PZ', max_length=20)),
                ('city', models.CharField(default='Cambridge', max_length=100)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('email', models.EmailField(default='paulaihiom@uniuyo.edu.ng', max_length=254)),
                ('email_note', models.CharField(blank=True, default='Response within 3–5 working days', max_length=255)),
                ('phone', models.CharField(blank=True, default='+234 803 333 444', max_length=50)),
                ('phone_note', models.CharField(blank=True, default='Mon – Fri, 09:00 – 17:00 GMT', max_length=255)),
                ('office_hours_days', models.CharField(blank=True, default='Tuesday & Thursday', max_length=100)),
                ('office_hours_times', models.CharField(blank=True, default='14:00 – 16:00 (term time only)', max_length=100)),
                ('office_hours_note', models.CharField(blank=True, default='Book via email in advance', max_length=255)),
                ('maps_url', models.URLField(blank=True, default='https://maps.google.com/?q=Department+of+Engineering+University+of+Cambridge')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('phd', 'PhD & Study'), ('research', 'Research'), ('books', 'Books'), ('general', 'General')], db_index=True, max_length=20)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon, e.g. 🎓', max_length=10)),
                ('label', models.CharField(help_text='Display label, e.g. Google Scholar', max_length=100)),
                ('href', models.URLField(help_text='Full URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
