# Generated by Django 6.0.7 on 2026-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='maps_url',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='A Google Maps embed src URL.'),
        ),
    ]
