# Generated by Django 6.0.7 on 2026-07-22 00:17

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Prof. A. P. Ihom', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='portrait',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Portrait'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, help_text='Shown in the footer — an academic motto or favorite quote.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(blank=True, help_text="Homepage hero teaser and meta-description fallback — a few sentences, not the full biography (that's about.AboutContent.full_bio)."),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_name',
            field=models.CharField(blank=True, help_text="Compact form for the navbar logo, e.g. 'Prof. A. P. Ihom'. Falls back to full_name in templates if left blank.", max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text="e.g. 'Professor of Materials and Metallurgical Engineering'", max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='label',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='home.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
