# Generated by Django 6.0.7 on 2026-07-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Proceedings'), ('review', 'Review Article')], default='journal', max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('external_url', models.URLField(blank=True)),
            ],
        ),
    ]
