# Generated by Django 6.0.7 on 2026-07-22 11:43

import cloudinary.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'title']},
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text="e.g. 'Ihom, A.P., Offiong, A.'", max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, help_text="Bare DOI only, e.g. '10.53294/ijfetr.2023.4.2.0015' — no 'https://doi.org/' prefix. Templates prepend it.", max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='external_url',
            field=models.URLField(blank=True, help_text='Fallback link (journal page, ResearchGate, etc.) — shown only when pdf_file is empty.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, help_text="Also holds 'Proceedings of...' for conference entries.", max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['year'], name='publication_year_7f8d21_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='publication_publica_3b16d8_idx'),
        ),
    ]
