# Generated by Django 6.0.7 on 2026-07-22 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'About Page Content', 'verbose_name_plural': 'About Page Content'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['year_joined']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='careermilestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careermilestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='academic_journey',
            field=models.TextField(blank=True, help_text='Short narrative shown above the career timeline.'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='full_bio',
            field=models.TextField(blank=True, help_text='Full biography — this is the long-form version. Profile.short_bio remains the homepage teaser.'),
        ),
        migrations.AlterField(
            model_name='careermilestone',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for a current position.', null=True),
        ),
        migrations.AlterField(
            model_name='careermilestone',
            name='organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='careermilestone',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text="e.g. 'PhD, Materials and Metallurgical Engineering'", max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, help_text="e.g. 'Technical', 'Software'", max_length=100),
        ),
    ]
